name: Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable RDP and Create User
        run: |
          # Buat user Fauzi dengan password kuat
          net user Fauzi "Fauzi@123" /add
          net localgroup administrators Fauzi /add

          # Aktifkan RDP
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Show IP
        run: |
          ipconfig
