name: rdp

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Download cloudflared
        run: |
          Invoke-WebRequest https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe

      - name: Enable RDP + buat user
        run: |
          net user Fauzi Abc123!! /add
          net localgroup administrators Fauzi /add
          reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Start cloudflared tunnel
        run: Start-Process -NoNewWindow -FilePath .\cloudflared.exe -ArgumentList "tunnel --url rdp://localhost:3389 --no-autoupdate"

      - name: Tampilkan info koneksi
        run: |
          Start-Sleep -Seconds 15
          Get-Content cloudflared.log -ErrorAction SilentlyContinue
