name: RDP Free Cloudflare

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Set RDP user
      run: |
        net user Fauzi "F@uZ!2025abc
        " /add
        net localgroup administrators Fauzi /add

    - name: Download Cloudflared
      run: Invoke-WebRequest -Uri https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe

    - name: Start Cloudflare Tunnel (TCP 3389)
      run: .\cloudflared.exe tunnel --url tcp://localhost:3389
